// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mixer/v1/attributes.proto

#ifndef PROTOBUF_INCLUDED_mixer_2fv1_2fattributes_2eproto
#define PROTOBUF_INCLUDED_mixer_2fv1_2fattributes_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "gogoproto/gogo.pb.h"
#include <google/protobuf/duration.pb.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_mixer_2fv1_2fattributes_2eproto 

namespace protobuf_mixer_2fv1_2fattributes_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[16];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_mixer_2fv1_2fattributes_2eproto
namespace istio {
namespace mixer {
namespace v1 {
class Attributes;
class AttributesDefaultTypeInternal;
extern AttributesDefaultTypeInternal _Attributes_default_instance_;
class Attributes_AttributeValue;
class Attributes_AttributeValueDefaultTypeInternal;
extern Attributes_AttributeValueDefaultTypeInternal _Attributes_AttributeValue_default_instance_;
class Attributes_AttributesEntry_DoNotUse;
class Attributes_AttributesEntry_DoNotUseDefaultTypeInternal;
extern Attributes_AttributesEntry_DoNotUseDefaultTypeInternal _Attributes_AttributesEntry_DoNotUse_default_instance_;
class Attributes_StringMap;
class Attributes_StringMapDefaultTypeInternal;
extern Attributes_StringMapDefaultTypeInternal _Attributes_StringMap_default_instance_;
class Attributes_StringMap_EntriesEntry_DoNotUse;
class Attributes_StringMap_EntriesEntry_DoNotUseDefaultTypeInternal;
extern Attributes_StringMap_EntriesEntry_DoNotUseDefaultTypeInternal _Attributes_StringMap_EntriesEntry_DoNotUse_default_instance_;
class CompressedAttributes;
class CompressedAttributesDefaultTypeInternal;
extern CompressedAttributesDefaultTypeInternal _CompressedAttributes_default_instance_;
class CompressedAttributes_BoolsEntry_DoNotUse;
class CompressedAttributes_BoolsEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_BoolsEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_BoolsEntry_DoNotUse_default_instance_;
class CompressedAttributes_BytesEntry_DoNotUse;
class CompressedAttributes_BytesEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_BytesEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_BytesEntry_DoNotUse_default_instance_;
class CompressedAttributes_DoublesEntry_DoNotUse;
class CompressedAttributes_DoublesEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_DoublesEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_DoublesEntry_DoNotUse_default_instance_;
class CompressedAttributes_DurationsEntry_DoNotUse;
class CompressedAttributes_DurationsEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_DurationsEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_DurationsEntry_DoNotUse_default_instance_;
class CompressedAttributes_Int64sEntry_DoNotUse;
class CompressedAttributes_Int64sEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_Int64sEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_Int64sEntry_DoNotUse_default_instance_;
class CompressedAttributes_StringMapsEntry_DoNotUse;
class CompressedAttributes_StringMapsEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_StringMapsEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_StringMapsEntry_DoNotUse_default_instance_;
class CompressedAttributes_StringsEntry_DoNotUse;
class CompressedAttributes_StringsEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_StringsEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_StringsEntry_DoNotUse_default_instance_;
class CompressedAttributes_TimestampsEntry_DoNotUse;
class CompressedAttributes_TimestampsEntry_DoNotUseDefaultTypeInternal;
extern CompressedAttributes_TimestampsEntry_DoNotUseDefaultTypeInternal _CompressedAttributes_TimestampsEntry_DoNotUse_default_instance_;
class StringMap;
class StringMapDefaultTypeInternal;
extern StringMapDefaultTypeInternal _StringMap_default_instance_;
class StringMap_EntriesEntry_DoNotUse;
class StringMap_EntriesEntry_DoNotUseDefaultTypeInternal;
extern StringMap_EntriesEntry_DoNotUseDefaultTypeInternal _StringMap_EntriesEntry_DoNotUse_default_instance_;
}  // namespace v1
}  // namespace mixer
}  // namespace istio
namespace google {
namespace protobuf {
template<> ::istio::mixer::v1::Attributes* Arena::CreateMaybeMessage<::istio::mixer::v1::Attributes>(Arena*);
template<> ::istio::mixer::v1::Attributes_AttributeValue* Arena::CreateMaybeMessage<::istio::mixer::v1::Attributes_AttributeValue>(Arena*);
template<> ::istio::mixer::v1::Attributes_AttributesEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::Attributes_AttributesEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::Attributes_StringMap* Arena::CreateMaybeMessage<::istio::mixer::v1::Attributes_StringMap>(Arena*);
template<> ::istio::mixer::v1::Attributes_StringMap_EntriesEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::Attributes_StringMap_EntriesEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_BoolsEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_BoolsEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_BytesEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_BytesEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_DoublesEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_DoublesEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_DurationsEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_DurationsEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_Int64sEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_Int64sEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_StringMapsEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_StringMapsEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_StringsEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_StringsEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::CompressedAttributes_TimestampsEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::CompressedAttributes_TimestampsEntry_DoNotUse>(Arena*);
template<> ::istio::mixer::v1::StringMap* Arena::CreateMaybeMessage<::istio::mixer::v1::StringMap>(Arena*);
template<> ::istio::mixer::v1::StringMap_EntriesEntry_DoNotUse* Arena::CreateMaybeMessage<::istio::mixer::v1::StringMap_EntriesEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace istio {
namespace mixer {
namespace v1 {

// ===================================================================

class Attributes_AttributesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Attributes_AttributesEntry_DoNotUse, 
    ::std::string, ::istio::mixer::v1::Attributes_AttributeValue,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<Attributes_AttributesEntry_DoNotUse, 
    ::std::string, ::istio::mixer::v1::Attributes_AttributeValue,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Attributes_AttributesEntry_DoNotUse();
  Attributes_AttributesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Attributes_AttributesEntry_DoNotUse& other);
  static const Attributes_AttributesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Attributes_AttributesEntry_DoNotUse*>(&_Attributes_AttributesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Attributes_AttributeValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:istio.mixer.v1.Attributes.AttributeValue) */ {
 public:
  Attributes_AttributeValue();
  virtual ~Attributes_AttributeValue();

  Attributes_AttributeValue(const Attributes_AttributeValue& from);

  inline Attributes_AttributeValue& operator=(const Attributes_AttributeValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Attributes_AttributeValue(Attributes_AttributeValue&& from) noexcept
    : Attributes_AttributeValue() {
    *this = ::std::move(from);
  }

  inline Attributes_AttributeValue& operator=(Attributes_AttributeValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Attributes_AttributeValue& default_instance();

  enum ValueCase {
    kStringValue = 2,
    kInt64Value = 3,
    kDoubleValue = 4,
    kBoolValue = 5,
    kBytesValue = 6,
    kTimestampValue = 7,
    kDurationValue = 8,
    kStringMapValue = 9,
    VALUE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Attributes_AttributeValue* internal_default_instance() {
    return reinterpret_cast<const Attributes_AttributeValue*>(
               &_Attributes_AttributeValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void UnsafeArenaSwap(Attributes_AttributeValue* other);
  void Swap(Attributes_AttributeValue* other);
  friend void swap(Attributes_AttributeValue& a, Attributes_AttributeValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Attributes_AttributeValue* New() const final {
    return CreateMaybeMessage<Attributes_AttributeValue>(NULL);
  }

  Attributes_AttributeValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Attributes_AttributeValue>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Attributes_AttributeValue& from);
  void MergeFrom(const Attributes_AttributeValue& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Attributes_AttributeValue* other);
  protected:
  explicit Attributes_AttributeValue(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string string_value = 2;
  private:
  bool has_string_value() const;
  public:
  void clear_string_value();
  static const int kStringValueFieldNumber = 2;
  const ::std::string& string_value() const;
  void set_string_value(const ::std::string& value);
  #if LANG_CXX11
  void set_string_value(::std::string&& value);
  #endif
  void set_string_value(const char* value);
  void set_string_value(const char* value, size_t size);
  ::std::string* mutable_string_value();
  ::std::string* release_string_value();
  void set_allocated_string_value(::std::string* string_value);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_string_value();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_string_value(
      ::std::string* string_value);

  // int64 int64_value = 3;
  private:
  bool has_int64_value() const;
  public:
  void clear_int64_value();
  static const int kInt64ValueFieldNumber = 3;
  ::google::protobuf::int64 int64_value() const;
  void set_int64_value(::google::protobuf::int64 value);

  // double double_value = 4;
  private:
  bool has_double_value() const;
  public:
  void clear_double_value();
  static const int kDoubleValueFieldNumber = 4;
  double double_value() const;
  void set_double_value(double value);

  // bool bool_value = 5;
  private:
  bool has_bool_value() const;
  public:
  void clear_bool_value();
  static const int kBoolValueFieldNumber = 5;
  bool bool_value() const;
  void set_bool_value(bool value);

  // bytes bytes_value = 6;
  private:
  bool has_bytes_value() const;
  public:
  void clear_bytes_value();
  static const int kBytesValueFieldNumber = 6;
  const ::std::string& bytes_value() const;
  void set_bytes_value(const ::std::string& value);
  #if LANG_CXX11
  void set_bytes_value(::std::string&& value);
  #endif
  void set_bytes_value(const char* value);
  void set_bytes_value(const void* value, size_t size);
  ::std::string* mutable_bytes_value();
  ::std::string* release_bytes_value();
  void set_allocated_bytes_value(::std::string* bytes_value);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_bytes_value();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_bytes_value(
      ::std::string* bytes_value);

  // .google.protobuf.Timestamp timestamp_value = 7;
  bool has_timestamp_value() const;
  void clear_timestamp_value();
  static const int kTimestampValueFieldNumber = 7;
  private:
  const ::google::protobuf::Timestamp& _internal_timestamp_value() const;
  public:
  const ::google::protobuf::Timestamp& timestamp_value() const;
  ::google::protobuf::Timestamp* release_timestamp_value();
  ::google::protobuf::Timestamp* mutable_timestamp_value();
  void set_allocated_timestamp_value(::google::protobuf::Timestamp* timestamp_value);
  void unsafe_arena_set_allocated_timestamp_value(
      ::google::protobuf::Timestamp* timestamp_value);
  ::google::protobuf::Timestamp* unsafe_arena_release_timestamp_value();

  // .google.protobuf.Duration duration_value = 8;
  bool has_duration_value() const;
  void clear_duration_value();
  static const int kDurationValueFieldNumber = 8;
  private:
  const ::google::protobuf::Duration& _internal_duration_value() const;
  public:
  const ::google::protobuf::Duration& duration_value() const;
  ::google::protobuf::Duration* release_duration_value();
  ::google::protobuf::Duration* mutable_duration_value();
  void set_allocated_duration_value(::google::protobuf::Duration* duration_value);
  void unsafe_arena_set_allocated_duration_value(
      ::google::protobuf::Duration* duration_value);
  ::google::protobuf::Duration* unsafe_arena_release_duration_value();

  // .istio.mixer.v1.Attributes.StringMap string_map_value = 9;
  bool has_string_map_value() const;
  void clear_string_map_value();
  static const int kStringMapValueFieldNumber = 9;
  private:
  const ::istio::mixer::v1::Attributes_StringMap& _internal_string_map_value() const;
  public:
  const ::istio::mixer::v1::Attributes_StringMap& string_map_value() const;
  ::istio::mixer::v1::Attributes_StringMap* release_string_map_value();
  ::istio::mixer::v1::Attributes_StringMap* mutable_string_map_value();
  void set_allocated_string_map_value(::istio::mixer::v1::Attributes_StringMap* string_map_value);
  void unsafe_arena_set_allocated_string_map_value(
      ::istio::mixer::v1::Attributes_StringMap* string_map_value);
  ::istio::mixer::v1::Attributes_StringMap* unsafe_arena_release_string_map_value();

  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:istio.mixer.v1.Attributes.AttributeValue)
 private:
  void set_has_string_value();
  void set_has_int64_value();
  void set_has_double_value();
  void set_has_bool_value();
  void set_has_bytes_value();
  void set_has_timestamp_value();
  void set_has_duration_value();
  void set_has_string_map_value();

  inline bool has_value() const;
  inline void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union ValueUnion {
    ValueUnion() {}
    ::google::protobuf::internal::ArenaStringPtr string_value_;
    ::google::protobuf::int64 int64_value_;
    double double_value_;
    bool bool_value_;
    ::google::protobuf::internal::ArenaStringPtr bytes_value_;
    ::google::protobuf::Timestamp* timestamp_value_;
    ::google::protobuf::Duration* duration_value_;
    ::istio::mixer::v1::Attributes_StringMap* string_map_value_;
  } value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_mixer_2fv1_2fattributes_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Attributes_StringMap_EntriesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Attributes_StringMap_EntriesEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<Attributes_StringMap_EntriesEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  Attributes_StringMap_EntriesEntry_DoNotUse();
  Attributes_StringMap_EntriesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Attributes_StringMap_EntriesEntry_DoNotUse& other);
  static const Attributes_StringMap_EntriesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Attributes_StringMap_EntriesEntry_DoNotUse*>(&_Attributes_StringMap_EntriesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Attributes_StringMap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:istio.mixer.v1.Attributes.StringMap) */ {
 public:
  Attributes_StringMap();
  virtual ~Attributes_StringMap();

  Attributes_StringMap(const Attributes_StringMap& from);

  inline Attributes_StringMap& operator=(const Attributes_StringMap& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Attributes_StringMap(Attributes_StringMap&& from) noexcept
    : Attributes_StringMap() {
    *this = ::std::move(from);
  }

  inline Attributes_StringMap& operator=(Attributes_StringMap&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Attributes_StringMap& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Attributes_StringMap* internal_default_instance() {
    return reinterpret_cast<const Attributes_StringMap*>(
               &_Attributes_StringMap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void UnsafeArenaSwap(Attributes_StringMap* other);
  void Swap(Attributes_StringMap* other);
  friend void swap(Attributes_StringMap& a, Attributes_StringMap& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Attributes_StringMap* New() const final {
    return CreateMaybeMessage<Attributes_StringMap>(NULL);
  }

  Attributes_StringMap* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Attributes_StringMap>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Attributes_StringMap& from);
  void MergeFrom(const Attributes_StringMap& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Attributes_StringMap* other);
  protected:
  explicit Attributes_StringMap(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      entries() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:istio.mixer.v1.Attributes.StringMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::MapField<
      Attributes_StringMap_EntriesEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > entries_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mixer_2fv1_2fattributes_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Attributes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:istio.mixer.v1.Attributes) */ {
 public:
  Attributes();
  virtual ~Attributes();

  Attributes(const Attributes& from);

  inline Attributes& operator=(const Attributes& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Attributes(Attributes&& from) noexcept
    : Attributes() {
    *this = ::std::move(from);
  }

  inline Attributes& operator=(Attributes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Attributes& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Attributes* internal_default_instance() {
    return reinterpret_cast<const Attributes*>(
               &_Attributes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void UnsafeArenaSwap(Attributes* other);
  void Swap(Attributes* other);
  friend void swap(Attributes& a, Attributes& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Attributes* New() const final {
    return CreateMaybeMessage<Attributes>(NULL);
  }

  Attributes* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Attributes>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Attributes& from);
  void MergeFrom(const Attributes& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Attributes* other);
  protected:
  explicit Attributes(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Attributes_AttributeValue AttributeValue;
  typedef Attributes_StringMap StringMap;

  // accessors -------------------------------------------------------

  // map<string, .istio.mixer.v1.Attributes.AttributeValue> attributes = 1;
  int attributes_size() const;
  void clear_attributes();
  static const int kAttributesFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::istio::mixer::v1::Attributes_AttributeValue >&
      attributes() const;
  ::google::protobuf::Map< ::std::string, ::istio::mixer::v1::Attributes_AttributeValue >*
      mutable_attributes();

  // @@protoc_insertion_point(class_scope:istio.mixer.v1.Attributes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::MapField<
      Attributes_AttributesEntry_DoNotUse,
      ::std::string, ::istio::mixer::v1::Attributes_AttributeValue,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > attributes_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mixer_2fv1_2fattributes_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CompressedAttributes_StringsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_StringsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_StringsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    0 > SuperType;
  CompressedAttributes_StringsEntry_DoNotUse();
  CompressedAttributes_StringsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_StringsEntry_DoNotUse& other);
  static const CompressedAttributes_StringsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_StringsEntry_DoNotUse*>(&_CompressedAttributes_StringsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes_Int64sEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_Int64sEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int64,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_Int64sEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int64,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    0 > SuperType;
  CompressedAttributes_Int64sEntry_DoNotUse();
  CompressedAttributes_Int64sEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_Int64sEntry_DoNotUse& other);
  static const CompressedAttributes_Int64sEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_Int64sEntry_DoNotUse*>(&_CompressedAttributes_Int64sEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes_DoublesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_DoublesEntry_DoNotUse, 
    ::google::protobuf::int32, double,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_DoublesEntry_DoNotUse, 
    ::google::protobuf::int32, double,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE,
    0 > SuperType;
  CompressedAttributes_DoublesEntry_DoNotUse();
  CompressedAttributes_DoublesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_DoublesEntry_DoNotUse& other);
  static const CompressedAttributes_DoublesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_DoublesEntry_DoNotUse*>(&_CompressedAttributes_DoublesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes_BoolsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_BoolsEntry_DoNotUse, 
    ::google::protobuf::int32, bool,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_BoolsEntry_DoNotUse, 
    ::google::protobuf::int32, bool,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
    0 > SuperType;
  CompressedAttributes_BoolsEntry_DoNotUse();
  CompressedAttributes_BoolsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_BoolsEntry_DoNotUse& other);
  static const CompressedAttributes_BoolsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_BoolsEntry_DoNotUse*>(&_CompressedAttributes_BoolsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes_TimestampsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_TimestampsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::Timestamp,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_TimestampsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::Timestamp,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  CompressedAttributes_TimestampsEntry_DoNotUse();
  CompressedAttributes_TimestampsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_TimestampsEntry_DoNotUse& other);
  static const CompressedAttributes_TimestampsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_TimestampsEntry_DoNotUse*>(&_CompressedAttributes_TimestampsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes_DurationsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_DurationsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::Duration,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_DurationsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::Duration,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  CompressedAttributes_DurationsEntry_DoNotUse();
  CompressedAttributes_DurationsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_DurationsEntry_DoNotUse& other);
  static const CompressedAttributes_DurationsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_DurationsEntry_DoNotUse*>(&_CompressedAttributes_DurationsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes_BytesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_BytesEntry_DoNotUse, 
    ::google::protobuf::int32, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_BYTES,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_BytesEntry_DoNotUse, 
    ::google::protobuf::int32, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_BYTES,
    0 > SuperType;
  CompressedAttributes_BytesEntry_DoNotUse();
  CompressedAttributes_BytesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_BytesEntry_DoNotUse& other);
  static const CompressedAttributes_BytesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_BytesEntry_DoNotUse*>(&_CompressedAttributes_BytesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes_StringMapsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<CompressedAttributes_StringMapsEntry_DoNotUse, 
    ::google::protobuf::int32, ::istio::mixer::v1::StringMap,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<CompressedAttributes_StringMapsEntry_DoNotUse, 
    ::google::protobuf::int32, ::istio::mixer::v1::StringMap,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  CompressedAttributes_StringMapsEntry_DoNotUse();
  CompressedAttributes_StringMapsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const CompressedAttributes_StringMapsEntry_DoNotUse& other);
  static const CompressedAttributes_StringMapsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const CompressedAttributes_StringMapsEntry_DoNotUse*>(&_CompressedAttributes_StringMapsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class CompressedAttributes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:istio.mixer.v1.CompressedAttributes) */ {
 public:
  CompressedAttributes();
  virtual ~CompressedAttributes();

  CompressedAttributes(const CompressedAttributes& from);

  inline CompressedAttributes& operator=(const CompressedAttributes& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CompressedAttributes(CompressedAttributes&& from) noexcept
    : CompressedAttributes() {
    *this = ::std::move(from);
  }

  inline CompressedAttributes& operator=(CompressedAttributes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const CompressedAttributes& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CompressedAttributes* internal_default_instance() {
    return reinterpret_cast<const CompressedAttributes*>(
               &_CompressedAttributes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    13;

  void UnsafeArenaSwap(CompressedAttributes* other);
  void Swap(CompressedAttributes* other);
  friend void swap(CompressedAttributes& a, CompressedAttributes& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CompressedAttributes* New() const final {
    return CreateMaybeMessage<CompressedAttributes>(NULL);
  }

  CompressedAttributes* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CompressedAttributes>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CompressedAttributes& from);
  void MergeFrom(const CompressedAttributes& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompressedAttributes* other);
  protected:
  explicit CompressedAttributes(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated string words = 1;
  int words_size() const;
  void clear_words();
  static const int kWordsFieldNumber = 1;
  const ::std::string& words(int index) const;
  ::std::string* mutable_words(int index);
  void set_words(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_words(int index, ::std::string&& value);
  #endif
  void set_words(int index, const char* value);
  void set_words(int index, const char* value, size_t size);
  ::std::string* add_words();
  void add_words(const ::std::string& value);
  #if LANG_CXX11
  void add_words(::std::string&& value);
  #endif
  void add_words(const char* value);
  void add_words(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& words() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_words();

  // map<sint32, sint32> strings = 2;
  int strings_size() const;
  void clear_strings();
  static const int kStringsFieldNumber = 2;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      strings() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_strings();

  // map<sint32, int64> int64s = 3;
  int int64s_size() const;
  void clear_int64s();
  static const int kInt64SFieldNumber = 3;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int64 >&
      int64s() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int64 >*
      mutable_int64s();

  // map<sint32, double> doubles = 4;
  int doubles_size() const;
  void clear_doubles();
  static const int kDoublesFieldNumber = 4;
  const ::google::protobuf::Map< ::google::protobuf::int32, double >&
      doubles() const;
  ::google::protobuf::Map< ::google::protobuf::int32, double >*
      mutable_doubles();

  // map<sint32, bool> bools = 5;
  int bools_size() const;
  void clear_bools();
  static const int kBoolsFieldNumber = 5;
  const ::google::protobuf::Map< ::google::protobuf::int32, bool >&
      bools() const;
  ::google::protobuf::Map< ::google::protobuf::int32, bool >*
      mutable_bools();

  // map<sint32, .google.protobuf.Timestamp> timestamps = 6 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
  int timestamps_size() const;
  void clear_timestamps();
  static const int kTimestampsFieldNumber = 6;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Timestamp >&
      timestamps() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Timestamp >*
      mutable_timestamps();

  // map<sint32, .google.protobuf.Duration> durations = 7 [(.gogoproto.nullable) = false, (.gogoproto.stdduration) = true];
  int durations_size() const;
  void clear_durations();
  static const int kDurationsFieldNumber = 7;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Duration >&
      durations() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Duration >*
      mutable_durations();

  // map<sint32, bytes> bytes = 8;
  int bytes_size() const;
  void clear_bytes();
  static const int kBytesFieldNumber = 8;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >&
      bytes() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >*
      mutable_bytes();

  // map<sint32, .istio.mixer.v1.StringMap> string_maps = 9 [(.gogoproto.nullable) = false];
  int string_maps_size() const;
  void clear_string_maps();
  static const int kStringMapsFieldNumber = 9;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::istio::mixer::v1::StringMap >&
      string_maps() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::istio::mixer::v1::StringMap >*
      mutable_string_maps();

  // @@protoc_insertion_point(class_scope:istio.mixer.v1.CompressedAttributes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedPtrField< ::std::string> words_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_StringsEntry_DoNotUse,
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      0 > strings_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_Int64sEntry_DoNotUse,
      ::google::protobuf::int32, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > int64s_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_DoublesEntry_DoNotUse,
      ::google::protobuf::int32, double,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE,
      0 > doubles_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_BoolsEntry_DoNotUse,
      ::google::protobuf::int32, bool,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
      0 > bools_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_TimestampsEntry_DoNotUse,
      ::google::protobuf::int32, ::google::protobuf::Timestamp,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > timestamps_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_DurationsEntry_DoNotUse,
      ::google::protobuf::int32, ::google::protobuf::Duration,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > durations_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_BytesEntry_DoNotUse,
      ::google::protobuf::int32, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_BYTES,
      0 > bytes_;
  ::google::protobuf::internal::MapField<
      CompressedAttributes_StringMapsEntry_DoNotUse,
      ::google::protobuf::int32, ::istio::mixer::v1::StringMap,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > string_maps_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mixer_2fv1_2fattributes_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StringMap_EntriesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<StringMap_EntriesEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<StringMap_EntriesEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
    0 > SuperType;
  StringMap_EntriesEntry_DoNotUse();
  StringMap_EntriesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const StringMap_EntriesEntry_DoNotUse& other);
  static const StringMap_EntriesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const StringMap_EntriesEntry_DoNotUse*>(&_StringMap_EntriesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class StringMap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:istio.mixer.v1.StringMap) */ {
 public:
  StringMap();
  virtual ~StringMap();

  StringMap(const StringMap& from);

  inline StringMap& operator=(const StringMap& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StringMap(StringMap&& from) noexcept
    : StringMap() {
    *this = ::std::move(from);
  }

  inline StringMap& operator=(StringMap&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const StringMap& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StringMap* internal_default_instance() {
    return reinterpret_cast<const StringMap*>(
               &_StringMap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    15;

  void UnsafeArenaSwap(StringMap* other);
  void Swap(StringMap* other);
  friend void swap(StringMap& a, StringMap& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StringMap* New() const final {
    return CreateMaybeMessage<StringMap>(NULL);
  }

  StringMap* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StringMap>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StringMap& from);
  void MergeFrom(const StringMap& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StringMap* other);
  protected:
  explicit StringMap(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<sint32, sint32> entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      entries() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:istio.mixer.v1.StringMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::MapField<
      StringMap_EntriesEntry_DoNotUse,
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_SINT32,
      0 > entries_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mixer_2fv1_2fattributes_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Attributes_AttributeValue

// string string_value = 2;
inline bool Attributes_AttributeValue::has_string_value() const {
  return value_case() == kStringValue;
}
inline void Attributes_AttributeValue::set_has_string_value() {
  _oneof_case_[0] = kStringValue;
}
inline void Attributes_AttributeValue::clear_string_value() {
  if (has_string_value()) {
    value_.string_value_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
    clear_has_value();
  }
}
inline const ::std::string& Attributes_AttributeValue::string_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.string_value)
  if (has_string_value()) {
    return value_.string_value_.Get();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void Attributes_AttributeValue::set_string_value(const ::std::string& value) {
  if (!has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:istio.mixer.v1.Attributes.AttributeValue.string_value)
}
#if LANG_CXX11
inline void Attributes_AttributeValue::set_string_value(::std::string&& value) {
  // @@protoc_insertion_point(field_set:istio.mixer.v1.Attributes.AttributeValue.string_value)
  if (!has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:istio.mixer.v1.Attributes.AttributeValue.string_value)
}
#endif
inline void Attributes_AttributeValue::set_string_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:istio.mixer.v1.Attributes.AttributeValue.string_value)
}
inline void Attributes_AttributeValue::set_string_value(const char* value,
                             size_t size) {
  if (!has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:istio.mixer.v1.Attributes.AttributeValue.string_value)
}
inline ::std::string* Attributes_AttributeValue::mutable_string_value() {
  if (!has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return value_.string_value_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_mutable:istio.mixer.v1.Attributes.AttributeValue.string_value)
}
inline ::std::string* Attributes_AttributeValue::release_string_value() {
  // @@protoc_insertion_point(field_release:istio.mixer.v1.Attributes.AttributeValue.string_value)
  if (has_string_value()) {
    clear_has_value();
    return value_.string_value_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
inline void Attributes_AttributeValue::set_allocated_string_value(::std::string* string_value) {
  if (!has_string_value()) {
    value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (string_value != NULL) {
    set_has_string_value();
    value_.string_value_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value,
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_set_allocated:istio.mixer.v1.Attributes.AttributeValue.string_value)
}
inline ::std::string* Attributes_AttributeValue::unsafe_arena_release_string_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:istio.mixer.v1.Attributes.AttributeValue.string_value)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (has_string_value()) {
    clear_has_value();
    return value_.string_value_.UnsafeArenaRelease(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
inline void Attributes_AttributeValue::unsafe_arena_set_allocated_string_value(::std::string* string_value) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (!has_string_value()) {
    value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (string_value) {
    set_has_string_value();
    value_.string_value_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value, GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:istio.mixer.v1.Attributes.AttributeValue.string_value)
}

// int64 int64_value = 3;
inline bool Attributes_AttributeValue::has_int64_value() const {
  return value_case() == kInt64Value;
}
inline void Attributes_AttributeValue::set_has_int64_value() {
  _oneof_case_[0] = kInt64Value;
}
inline void Attributes_AttributeValue::clear_int64_value() {
  if (has_int64_value()) {
    value_.int64_value_ = GOOGLE_LONGLONG(0);
    clear_has_value();
  }
}
inline ::google::protobuf::int64 Attributes_AttributeValue::int64_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.int64_value)
  if (has_int64_value()) {
    return value_.int64_value_;
  }
  return GOOGLE_LONGLONG(0);
}
inline void Attributes_AttributeValue::set_int64_value(::google::protobuf::int64 value) {
  if (!has_int64_value()) {
    clear_value();
    set_has_int64_value();
  }
  value_.int64_value_ = value;
  // @@protoc_insertion_point(field_set:istio.mixer.v1.Attributes.AttributeValue.int64_value)
}

// double double_value = 4;
inline bool Attributes_AttributeValue::has_double_value() const {
  return value_case() == kDoubleValue;
}
inline void Attributes_AttributeValue::set_has_double_value() {
  _oneof_case_[0] = kDoubleValue;
}
inline void Attributes_AttributeValue::clear_double_value() {
  if (has_double_value()) {
    value_.double_value_ = 0;
    clear_has_value();
  }
}
inline double Attributes_AttributeValue::double_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.double_value)
  if (has_double_value()) {
    return value_.double_value_;
  }
  return 0;
}
inline void Attributes_AttributeValue::set_double_value(double value) {
  if (!has_double_value()) {
    clear_value();
    set_has_double_value();
  }
  value_.double_value_ = value;
  // @@protoc_insertion_point(field_set:istio.mixer.v1.Attributes.AttributeValue.double_value)
}

// bool bool_value = 5;
inline bool Attributes_AttributeValue::has_bool_value() const {
  return value_case() == kBoolValue;
}
inline void Attributes_AttributeValue::set_has_bool_value() {
  _oneof_case_[0] = kBoolValue;
}
inline void Attributes_AttributeValue::clear_bool_value() {
  if (has_bool_value()) {
    value_.bool_value_ = false;
    clear_has_value();
  }
}
inline bool Attributes_AttributeValue::bool_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.bool_value)
  if (has_bool_value()) {
    return value_.bool_value_;
  }
  return false;
}
inline void Attributes_AttributeValue::set_bool_value(bool value) {
  if (!has_bool_value()) {
    clear_value();
    set_has_bool_value();
  }
  value_.bool_value_ = value;
  // @@protoc_insertion_point(field_set:istio.mixer.v1.Attributes.AttributeValue.bool_value)
}

// bytes bytes_value = 6;
inline bool Attributes_AttributeValue::has_bytes_value() const {
  return value_case() == kBytesValue;
}
inline void Attributes_AttributeValue::set_has_bytes_value() {
  _oneof_case_[0] = kBytesValue;
}
inline void Attributes_AttributeValue::clear_bytes_value() {
  if (has_bytes_value()) {
    value_.bytes_value_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
    clear_has_value();
  }
}
inline const ::std::string& Attributes_AttributeValue::bytes_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
  if (has_bytes_value()) {
    return value_.bytes_value_.Get();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void Attributes_AttributeValue::set_bytes_value(const ::std::string& value) {
  if (!has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
}
#if LANG_CXX11
inline void Attributes_AttributeValue::set_bytes_value(::std::string&& value) {
  // @@protoc_insertion_point(field_set:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
  if (!has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
}
#endif
inline void Attributes_AttributeValue::set_bytes_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
}
inline void Attributes_AttributeValue::set_bytes_value(const void* value,
                             size_t size) {
  if (!has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
}
inline ::std::string* Attributes_AttributeValue::mutable_bytes_value() {
  if (!has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return value_.bytes_value_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_mutable:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
}
inline ::std::string* Attributes_AttributeValue::release_bytes_value() {
  // @@protoc_insertion_point(field_release:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
  if (has_bytes_value()) {
    clear_has_value();
    return value_.bytes_value_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
inline void Attributes_AttributeValue::set_allocated_bytes_value(::std::string* bytes_value) {
  if (!has_bytes_value()) {
    value_.bytes_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (bytes_value != NULL) {
    set_has_bytes_value();
    value_.bytes_value_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bytes_value,
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_set_allocated:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
}
inline ::std::string* Attributes_AttributeValue::unsafe_arena_release_bytes_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (has_bytes_value()) {
    clear_has_value();
    return value_.bytes_value_.UnsafeArenaRelease(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  } else {
    return NULL;
  }
}
inline void Attributes_AttributeValue::unsafe_arena_set_allocated_bytes_value(::std::string* bytes_value) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (!has_bytes_value()) {
    value_.bytes_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (bytes_value) {
    set_has_bytes_value();
    value_.bytes_value_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bytes_value, GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:istio.mixer.v1.Attributes.AttributeValue.bytes_value)
}

// .google.protobuf.Timestamp timestamp_value = 7;
inline bool Attributes_AttributeValue::has_timestamp_value() const {
  return value_case() == kTimestampValue;
}
inline void Attributes_AttributeValue::set_has_timestamp_value() {
  _oneof_case_[0] = kTimestampValue;
}
inline const ::google::protobuf::Timestamp& Attributes_AttributeValue::_internal_timestamp_value() const {
  return *value_.timestamp_value_;
}
inline ::google::protobuf::Timestamp* Attributes_AttributeValue::release_timestamp_value() {
  // @@protoc_insertion_point(field_release:istio.mixer.v1.Attributes.AttributeValue.timestamp_value)
  if (has_timestamp_value()) {
    clear_has_value();
      ::google::protobuf::Timestamp* temp = value_.timestamp_value_;
    if (GetArenaNoVirtual() != NULL) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    value_.timestamp_value_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::google::protobuf::Timestamp& Attributes_AttributeValue::timestamp_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.timestamp_value)
  return has_timestamp_value()
      ? *value_.timestamp_value_
      : *reinterpret_cast< ::google::protobuf::Timestamp*>(&::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* Attributes_AttributeValue::unsafe_arena_release_timestamp_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:istio.mixer.v1.Attributes.AttributeValue.timestamp_value)
  if (has_timestamp_value()) {
    clear_has_value();
    ::google::protobuf::Timestamp* temp = value_.timestamp_value_;
    value_.timestamp_value_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Attributes_AttributeValue::unsafe_arena_set_allocated_timestamp_value(::google::protobuf::Timestamp* timestamp_value) {
  clear_value();
  if (timestamp_value) {
    set_has_timestamp_value();
    value_.timestamp_value_ = timestamp_value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:istio.mixer.v1.Attributes.AttributeValue.timestamp_value)
}
inline ::google::protobuf::Timestamp* Attributes_AttributeValue::mutable_timestamp_value() {
  if (!has_timestamp_value()) {
    clear_value();
    set_has_timestamp_value();
    value_.timestamp_value_ = CreateMaybeMessage< ::google::protobuf::Timestamp >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:istio.mixer.v1.Attributes.AttributeValue.timestamp_value)
  return value_.timestamp_value_;
}

// .google.protobuf.Duration duration_value = 8;
inline bool Attributes_AttributeValue::has_duration_value() const {
  return value_case() == kDurationValue;
}
inline void Attributes_AttributeValue::set_has_duration_value() {
  _oneof_case_[0] = kDurationValue;
}
inline const ::google::protobuf::Duration& Attributes_AttributeValue::_internal_duration_value() const {
  return *value_.duration_value_;
}
inline ::google::protobuf::Duration* Attributes_AttributeValue::release_duration_value() {
  // @@protoc_insertion_point(field_release:istio.mixer.v1.Attributes.AttributeValue.duration_value)
  if (has_duration_value()) {
    clear_has_value();
      ::google::protobuf::Duration* temp = value_.duration_value_;
    if (GetArenaNoVirtual() != NULL) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    value_.duration_value_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::google::protobuf::Duration& Attributes_AttributeValue::duration_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.duration_value)
  return has_duration_value()
      ? *value_.duration_value_
      : *reinterpret_cast< ::google::protobuf::Duration*>(&::google::protobuf::_Duration_default_instance_);
}
inline ::google::protobuf::Duration* Attributes_AttributeValue::unsafe_arena_release_duration_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:istio.mixer.v1.Attributes.AttributeValue.duration_value)
  if (has_duration_value()) {
    clear_has_value();
    ::google::protobuf::Duration* temp = value_.duration_value_;
    value_.duration_value_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Attributes_AttributeValue::unsafe_arena_set_allocated_duration_value(::google::protobuf::Duration* duration_value) {
  clear_value();
  if (duration_value) {
    set_has_duration_value();
    value_.duration_value_ = duration_value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:istio.mixer.v1.Attributes.AttributeValue.duration_value)
}
inline ::google::protobuf::Duration* Attributes_AttributeValue::mutable_duration_value() {
  if (!has_duration_value()) {
    clear_value();
    set_has_duration_value();
    value_.duration_value_ = CreateMaybeMessage< ::google::protobuf::Duration >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:istio.mixer.v1.Attributes.AttributeValue.duration_value)
  return value_.duration_value_;
}

// .istio.mixer.v1.Attributes.StringMap string_map_value = 9;
inline bool Attributes_AttributeValue::has_string_map_value() const {
  return value_case() == kStringMapValue;
}
inline void Attributes_AttributeValue::set_has_string_map_value() {
  _oneof_case_[0] = kStringMapValue;
}
inline void Attributes_AttributeValue::clear_string_map_value() {
  if (has_string_map_value()) {
    if (GetArenaNoVirtual() == NULL) {
      delete value_.string_map_value_;
    }
    clear_has_value();
  }
}
inline const ::istio::mixer::v1::Attributes_StringMap& Attributes_AttributeValue::_internal_string_map_value() const {
  return *value_.string_map_value_;
}
inline ::istio::mixer::v1::Attributes_StringMap* Attributes_AttributeValue::release_string_map_value() {
  // @@protoc_insertion_point(field_release:istio.mixer.v1.Attributes.AttributeValue.string_map_value)
  if (has_string_map_value()) {
    clear_has_value();
      ::istio::mixer::v1::Attributes_StringMap* temp = value_.string_map_value_;
    if (GetArenaNoVirtual() != NULL) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    value_.string_map_value_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::istio::mixer::v1::Attributes_StringMap& Attributes_AttributeValue::string_map_value() const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.Attributes.AttributeValue.string_map_value)
  return has_string_map_value()
      ? *value_.string_map_value_
      : *reinterpret_cast< ::istio::mixer::v1::Attributes_StringMap*>(&::istio::mixer::v1::_Attributes_StringMap_default_instance_);
}
inline ::istio::mixer::v1::Attributes_StringMap* Attributes_AttributeValue::unsafe_arena_release_string_map_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:istio.mixer.v1.Attributes.AttributeValue.string_map_value)
  if (has_string_map_value()) {
    clear_has_value();
    ::istio::mixer::v1::Attributes_StringMap* temp = value_.string_map_value_;
    value_.string_map_value_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Attributes_AttributeValue::unsafe_arena_set_allocated_string_map_value(::istio::mixer::v1::Attributes_StringMap* string_map_value) {
  clear_value();
  if (string_map_value) {
    set_has_string_map_value();
    value_.string_map_value_ = string_map_value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:istio.mixer.v1.Attributes.AttributeValue.string_map_value)
}
inline ::istio::mixer::v1::Attributes_StringMap* Attributes_AttributeValue::mutable_string_map_value() {
  if (!has_string_map_value()) {
    clear_value();
    set_has_string_map_value();
    value_.string_map_value_ = CreateMaybeMessage< ::istio::mixer::v1::Attributes_StringMap >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:istio.mixer.v1.Attributes.AttributeValue.string_map_value)
  return value_.string_map_value_;
}

inline bool Attributes_AttributeValue::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void Attributes_AttributeValue::clear_has_value() {
  _oneof_case_[0] = VALUE_NOT_SET;
}
inline Attributes_AttributeValue::ValueCase Attributes_AttributeValue::value_case() const {
  return Attributes_AttributeValue::ValueCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Attributes_StringMap

// map<string, string> entries = 1;
inline int Attributes_StringMap::entries_size() const {
  return entries_.size();
}
inline void Attributes_StringMap::clear_entries() {
  entries_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Attributes_StringMap::entries() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.Attributes.StringMap.entries)
  return entries_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Attributes_StringMap::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.Attributes.StringMap.entries)
  return entries_.MutableMap();
}

// -------------------------------------------------------------------

// Attributes

// map<string, .istio.mixer.v1.Attributes.AttributeValue> attributes = 1;
inline int Attributes::attributes_size() const {
  return attributes_.size();
}
inline void Attributes::clear_attributes() {
  attributes_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::istio::mixer::v1::Attributes_AttributeValue >&
Attributes::attributes() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.Attributes.attributes)
  return attributes_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::istio::mixer::v1::Attributes_AttributeValue >*
Attributes::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.Attributes.attributes)
  return attributes_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// CompressedAttributes

// repeated string words = 1;
inline int CompressedAttributes::words_size() const {
  return words_.size();
}
inline void CompressedAttributes::clear_words() {
  words_.Clear();
}
inline const ::std::string& CompressedAttributes::words(int index) const {
  // @@protoc_insertion_point(field_get:istio.mixer.v1.CompressedAttributes.words)
  return words_.Get(index);
}
inline ::std::string* CompressedAttributes::mutable_words(int index) {
  // @@protoc_insertion_point(field_mutable:istio.mixer.v1.CompressedAttributes.words)
  return words_.Mutable(index);
}
inline void CompressedAttributes::set_words(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:istio.mixer.v1.CompressedAttributes.words)
  words_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void CompressedAttributes::set_words(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:istio.mixer.v1.CompressedAttributes.words)
  words_.Mutable(index)->assign(std::move(value));
}
#endif
inline void CompressedAttributes::set_words(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  words_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:istio.mixer.v1.CompressedAttributes.words)
}
inline void CompressedAttributes::set_words(int index, const char* value, size_t size) {
  words_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:istio.mixer.v1.CompressedAttributes.words)
}
inline ::std::string* CompressedAttributes::add_words() {
  // @@protoc_insertion_point(field_add_mutable:istio.mixer.v1.CompressedAttributes.words)
  return words_.Add();
}
inline void CompressedAttributes::add_words(const ::std::string& value) {
  words_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:istio.mixer.v1.CompressedAttributes.words)
}
#if LANG_CXX11
inline void CompressedAttributes::add_words(::std::string&& value) {
  words_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:istio.mixer.v1.CompressedAttributes.words)
}
#endif
inline void CompressedAttributes::add_words(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  words_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:istio.mixer.v1.CompressedAttributes.words)
}
inline void CompressedAttributes::add_words(const char* value, size_t size) {
  words_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:istio.mixer.v1.CompressedAttributes.words)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CompressedAttributes::words() const {
  // @@protoc_insertion_point(field_list:istio.mixer.v1.CompressedAttributes.words)
  return words_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CompressedAttributes::mutable_words() {
  // @@protoc_insertion_point(field_mutable_list:istio.mixer.v1.CompressedAttributes.words)
  return &words_;
}

// map<sint32, sint32> strings = 2;
inline int CompressedAttributes::strings_size() const {
  return strings_.size();
}
inline void CompressedAttributes::clear_strings() {
  strings_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
CompressedAttributes::strings() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.strings)
  return strings_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
CompressedAttributes::mutable_strings() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.strings)
  return strings_.MutableMap();
}

// map<sint32, int64> int64s = 3;
inline int CompressedAttributes::int64s_size() const {
  return int64s_.size();
}
inline void CompressedAttributes::clear_int64s() {
  int64s_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int64 >&
CompressedAttributes::int64s() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.int64s)
  return int64s_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int64 >*
CompressedAttributes::mutable_int64s() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.int64s)
  return int64s_.MutableMap();
}

// map<sint32, double> doubles = 4;
inline int CompressedAttributes::doubles_size() const {
  return doubles_.size();
}
inline void CompressedAttributes::clear_doubles() {
  doubles_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, double >&
CompressedAttributes::doubles() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.doubles)
  return doubles_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, double >*
CompressedAttributes::mutable_doubles() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.doubles)
  return doubles_.MutableMap();
}

// map<sint32, bool> bools = 5;
inline int CompressedAttributes::bools_size() const {
  return bools_.size();
}
inline void CompressedAttributes::clear_bools() {
  bools_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, bool >&
CompressedAttributes::bools() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.bools)
  return bools_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, bool >*
CompressedAttributes::mutable_bools() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.bools)
  return bools_.MutableMap();
}

// map<sint32, .google.protobuf.Timestamp> timestamps = 6 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
inline int CompressedAttributes::timestamps_size() const {
  return timestamps_.size();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Timestamp >&
CompressedAttributes::timestamps() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.timestamps)
  return timestamps_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Timestamp >*
CompressedAttributes::mutable_timestamps() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.timestamps)
  return timestamps_.MutableMap();
}

// map<sint32, .google.protobuf.Duration> durations = 7 [(.gogoproto.nullable) = false, (.gogoproto.stdduration) = true];
inline int CompressedAttributes::durations_size() const {
  return durations_.size();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Duration >&
CompressedAttributes::durations() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.durations)
  return durations_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::Duration >*
CompressedAttributes::mutable_durations() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.durations)
  return durations_.MutableMap();
}

// map<sint32, bytes> bytes = 8;
inline int CompressedAttributes::bytes_size() const {
  return bytes_.size();
}
inline void CompressedAttributes::clear_bytes() {
  bytes_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >&
CompressedAttributes::bytes() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.bytes)
  return bytes_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >*
CompressedAttributes::mutable_bytes() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.bytes)
  return bytes_.MutableMap();
}

// map<sint32, .istio.mixer.v1.StringMap> string_maps = 9 [(.gogoproto.nullable) = false];
inline int CompressedAttributes::string_maps_size() const {
  return string_maps_.size();
}
inline void CompressedAttributes::clear_string_maps() {
  string_maps_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::istio::mixer::v1::StringMap >&
CompressedAttributes::string_maps() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.CompressedAttributes.string_maps)
  return string_maps_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::istio::mixer::v1::StringMap >*
CompressedAttributes::mutable_string_maps() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.CompressedAttributes.string_maps)
  return string_maps_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// StringMap

// map<sint32, sint32> entries = 1;
inline int StringMap::entries_size() const {
  return entries_.size();
}
inline void StringMap::clear_entries() {
  entries_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
StringMap::entries() const {
  // @@protoc_insertion_point(field_map:istio.mixer.v1.StringMap.entries)
  return entries_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
StringMap::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_map:istio.mixer.v1.StringMap.entries)
  return entries_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace mixer
}  // namespace istio

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_mixer_2fv1_2fattributes_2eproto
