// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/v1beta1/value_type.proto

#include "policy/v1beta1/value_type.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace istio {
namespace policy {
namespace v1beta1 {
}  // namespace v1beta1
}  // namespace policy
}  // namespace istio
namespace protobuf_policy_2fv1beta1_2fvalue_5ftype_2eproto {
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "policy/v1beta1/value_type.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\037policy/v1beta1/value_type.proto\022\024istio"
      ".policy.v1beta1*\273\001\n\tValueType\022\032\n\026VALUE_T"
      "YPE_UNSPECIFIED\020\000\022\n\n\006STRING\020\001\022\t\n\005INT64\020\002"
      "\022\n\n\006DOUBLE\020\003\022\010\n\004BOOL\020\004\022\r\n\tTIMESTAMP\020\005\022\016\n"
      "\nIP_ADDRESS\020\006\022\021\n\rEMAIL_ADDRESS\020\007\022\007\n\003URI\020"
      "\010\022\014\n\010DNS_NAME\020\t\022\014\n\010DURATION\020\n\022\016\n\nSTRING_"
      "MAP\020\013B\035Z\033istio.io/api/policy/v1beta1b\006pr"
      "oto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 284);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "policy/v1beta1/value_type.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_policy_2fv1beta1_2fvalue_5ftype_2eproto
namespace istio {
namespace policy {
namespace v1beta1 {
const ::google::protobuf::EnumDescriptor* ValueType_descriptor() {
  protobuf_policy_2fv1beta1_2fvalue_5ftype_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_policy_2fv1beta1_2fvalue_5ftype_2eproto::file_level_enum_descriptors[0];
}
bool ValueType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1beta1
}  // namespace policy
}  // namespace istio

// @@protoc_insertion_point(global_scope)
